# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .       # installs your package from pyproject.toml

sphinx:
  configuration: docs/conf.py
