version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - gfortran
    - gcc
    - libnetcdf-dev
    - build-essential

python:
  install:
    - method: pip
      packages:
        - sphinx_rtd_theme
    - method: pip
      path: .   # installs your package from pyproject.toml

sphinx:
  configuration: docs/conf.py